name: Terraform

on:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/112192593580/locations/global/workloadIdentityPools/identity-pool/providers/github-provider
          service_account: github-sa@terraform-gcp-resources.iam.gserviceaccount.com

      - uses: hashicorp/setup-terraform@v3
      - name: checkout folder
        run: |
          pwd
          cd /GCS-module/environment/dev
          pwd
          ls -la
      - name: terraform init
        run: |
          terraform init
          terraform validate
      - name: terraform plan
        run: terraform plan
      - name: terraform apply 
        run: terraform apply --auto-approve
       
